function net = PredictNet(XtrainSeq, YtrainSeq)
numFeatures = 6;
numResponses = 1;
numHiddenUnits = 400;

layers = [...
    sequenceInputLayer(numFeatures)
    fullyConnectedLayer(30)
    eluLayer
    lstmLayer(numHiddenUnits)
    reluLayer
    fullyConnectedLayer(30)
    fullyConnectedLayer(numResponses)
    regressionLayer];

options = trainingOptions( ...
    'adam', ...
    'MaxEpochs',2000, ...
    'GradientThreshold',1, ...
    'InitialLearnRate',1e-3, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',75, ...
    'LearnRateDropFactor',0.95, ...
    'ExecutionEnvironment','gpu',...
    'Verbose',0, ...
    'Plots','training-progress');

net = trainNetwork(XtrainSeq,YtrainSeq,layers,options);
end