function net = PredictNet(XtrainSeq, YtrainSeq)
numFeatures = 1;
numResponses = 1;
numHiddenUnits = 300;

layers = [...
    sequenceInputLayer(numFeatures)
    lstmLayer(numHiddenUnits)
    eluLayer
    fullyConnectedLayer(numResponses)
    lstmLayer(numHiddenUnits)
    reluLayer
    fullyConnectedLayer(numResponses)
    regressionLayer];

options = trainingOptions('adam', ...
    'MaxEpochs',250, ...
    'GradientThreshold',1, ...
    'InitialLearnRate',0.001, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',125, ...
    'LearnRateDropFactor',0.2, ...
    'ExecutionEnvironment','gpu',...
    'Verbose',0, ...
    'Plots','training-progress');

net = trainNetwork(XtrainSeq,YtrainSeq,layers,options);
end