% Load Data
clc; clear;
format long
path_daily = './data/COVID19/daily_info.csv';
data = StatisticsAnalysis( ...
    'TablePath', path_daily, ...
    'ImportOptions', { ...
        'VariableTypes', { ...
            'new_vaccinations', 'double';
            'total_vaccinations', 'double' ...
            }; ...
        'SelectedVariableNames', {'date', 'new_cases', 'total_cases'} ...
        }, ...
    'SelectTableOptions', { ...
        'location', 'China'; ... Country
        'date', { ...
            arange(["2020-01-01", "2020-12-31"], 'closed')
            } ... Time Range
        } ... % Will Automatically Select Table Before Importing Table
    ).Table;

data = tableMissingValuesHelper(data, ...
    'VariableNames', {'new_cases', 'total_cases'}, ...
    'Style', 'Increment-Addition' ...
    );
data = StatisticsAnalysis( ...
    'Table', data, ...
    'TagsGenerateOptions', { ...
        'TagContinuity', [0 1 1]; ...
        'CustomTagName', {'centralization', [0 1 1]}; ...
        'QuickStyle', {'MissingCount'} ...
        }...
    ).Table;

new_cases = table2array(data(:,2));
total_cases = table2array(data(:,3))';

coeff = polyfit(1:size(total_cases,2),total_cases,1);
linear = @(x) coeff(1)*x + coeff(2);
xlist = 1:size(total_cases,2);
ylist = linear(xlist);

plot(total_cases);
hold on;
plot(ylist);