function net = RegressionNet(XtrainSeq, YtrainSeq)
numFeatures = 8;
numResponses = 1;

layers = [...
    sequenceInputLayer(numFeatures)
    fullyConnectedLayer(300)
    reluLayer
    fullyConnectedLayer(300)
    reluLayer
    fullyConnectedLayer(300)
    reluLayer
    fullyConnectedLayer(numResponses)
    regressionLayer];

options = trainingOptions( ...
    'adam', ...
    'MaxEpochs',2000, ...
    'SequenceLength','longest',...
    'GradientThreshold',1, ...
    'InitialLearnRate',1e-3, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',75, ...
    'LearnRateDropFactor',0.95, ...
    'ExecutionEnvironment','gpu',...
    'Verbose',0, ...
    'Plots','training-progress');

net = trainNetwork(XtrainSeq,YtrainSeq,layers,options);
end